# Generated by Django 4.1.7 on 2023-06-12 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='good',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shopAPI.good'),
            preserve_default=False,
        ),
    ]
